### PR TITLE
Change .apply() function applying to .call() calling

### LINKED ISSUE #20: `find` function requires array as the second argument
Read the doc.

```
find([1, 2], function (x) { return x === 2; }); // 2
```

Try to reproduce in my code.

```
import find from 'array.prototype.find';
...
find(headers, (header) => {
  // do something with header...
});
```

Result: `TypeError: Array#find: predicate must be a function`

Dive into the `index.js` (the root file of the lib), and see 

```
return implementation.apply(array, predicate);
```

But [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply) says that the second argument of `.apply` should be an array! So, in my example 

```
import find from 'array.prototype.find';
...
find(headers, [(header) => {
  // do something with header...
}]);
// note the brackets
```

works well. Think, either docs, either code of the lib should be changed.

### PR DESCRIPTION
**Pull request by DmitryKa**
Fix #20 
Are any objections against using `.call()` instead of `.apply()`?

### CODE REVIEW

**Comment by DmitryKa** [comment]
@ljharb Added tests. Also found one more bug -- in one test we pass optional context, but there wasn't ability to do it in single `.find()` function with previous code.

File: index.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ var slice = Array.prototype.slice;
 
 var boundFindShim = function find(array, predicate) {
 	ES.RequireObjectCoercible(array);
-	return implementation.call(array, predicate);
```
Comment (ljharb) [inline index.js]: I think this would be better as `implementation.apply(array, arguments)`. Indexing into arguments objects (or arrays) is generally not a good idea.

File: tests/test.js [hunk 2]
```diff
@@ -108,3 +108,19 @@ describe('shim', function() {
 		delete Object.prototype[1];
 	});
 });
+
+describe('single function', function() {
+	var findAsFunction = function(func) {
+			return find.call(undefined, this, func, arguments[1]);
```
Comment (ljharb) [inline tests/test.js]: this line needs deindenting a level

Comment (ljharb) [inline tests/test.js]: Instead of creating `findAsFunction`, i think what we really want is just to use `find` directly here?

Comment (DmitryKa) [inline tests/test.js]: we want to use `find`, but in tests `call` is used and it passes first arg as context, but we want to pass it as a just argument.

Comment (DmitryKa) [inline tests/test.js]: Changed code, maybe it will be more clear

Comment (ljharb) [inline tests/test.js]: Ah. Do you want `Function.call.bind(find)`?

Comment (DmitryKa) [inline tests/test.js]: Sorry, didn't get it. What should it do? I want to call `find` but pass params there and add current context as a first param.

**Comment by DmitryKa** [comment]
@ljharb Sorry, do you mean a git squash? If so, will it require new PR, or is there a possibility to rewrite current?

**Comment by ljharb** [comment]
@DmitryKa yep! you can simply force push to your "Array.prototype.find" branch, and the PR will update. Also if you prefer, I can take care of it for you.
